# Generated by Django 3.1.1 on 2020-10-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('primeiro_nome', models.CharField(max_length=20)),
                ('ultimo_nome', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'funcionario',
                'verbose_name_plural': 'funcionarios',
                'ordering': ['primeiro_nome'],
            },
        ),
    ]
