# Generated by Django 3.1.1 on 2020-09-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
