# Generated by Django 3.1.1 on 2020-09-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20200929_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='created',
            new_name='criado_em',
        ),
    ]
