# Generated by Django 3.1.1 on 2020-09-30 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0003_auto_20200929_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='empresas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
