# Generated by Django 3.1.1 on 2020-09-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0004_funcionario_empresas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='empresas',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresas',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
    ]
